### ISSUE TITLE
Comparison to NaN.

### ISSUE THREAD

**Issue by hodovani** [wolverton-research-group/qmpy#114]
Sorry, Comparison to NaN is useless. Nothing is equal to NaN, not even NaN. Use Number.isNaN(). I found it here https://github.com/wolverton-research-group/qmpy/blob/master/qmpy/web/static/js/jsmol/j2s/J/adapter/writers/QCJSONWriter.js#L425. Could you please check this when you have a free sec.

**Comment by tachyontraveler** [comment]
Hi @hodovani , Thanks for reporting the issue. I'm currently working on an update to Javascript files in qmpy. I'll add your suggested fix to that upcoming PR. I will keep this issue open until the javascript updates are finished.

**Comment by hodovani** [comment]
@tachyontraveler thanks :)
