### ISSUE TITLE
[OPTIMADE API] meta->data_available and meta->data_returned provide incorrect values

### ISSUE THREAD

**Issue by ml-evs** [wolverton-research-group/qmpy#116]
Just noticed something else when generating the table for this paper, seems appropriate to raise a separate issue.

It looks like you have `data_available` and `data_returned` mixed up in some of your responses (see [§4.3 of the spec](https://github.com/Materials-Consortia/OPTiMaDe/blob/develop/optimade.rst#json-response-schema-common-fields)):
- The `meta` field `data_returned` is supposed to give the non-paginated number of results for a filter (currently it gives the number of entries on that page of the response) 
- The `meta` field `data_available` is supposed to give the total number of entries available at that endpoint (i.e. all structures in the database). It looks like this value is currently taking what `data_returned` is meant to give.

Example: http://oqmd.org/optimade/v1/structures?filter=elements%20HAS%20ANY%20%22C%22,%22Si%22,%22Ge%22,%22Sn%22,%22Pb%22%20AND%20nelements=2

| Field  | Current value | Expected value |
|:--:|---:|--:|
| `data_returned` | 50 | 11011 |
| `data_available` | 11011 | 815654 (all of OQMD) |

**Comment by tachyontraveler** [comment]
Thanks for reporting this, @ml-evs . I'll fix it today.

**Comment by tachyontraveler** [comment]
Fixed it.
