### ISSUE TITLE
Compatibility with django 1.7

### ISSUE THREAD

**Issue by michaelagibson** [wolverton-research-group/qmpy#13]
I am having a lot of backwards compatibility issues with django and qmpy. I am using django 1.7 on Ubuntu 14.04.
I am getting the error:
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
I will attempt to work through this and post my solution, if I am successful. 
If qmpy is not forward-compatible with the current versions of django, could you specify in the documentation which versions of django qmpy is compatible with?

**Comment by WardLT** [comment]
I have had success in getting qmpy working with Django 1.7, but it required a slight modification to `./qmpy/__init__.py`. Django 1.7 initializes the models a little differently than 1.6 (which is what we typically run). 

You'll need to add the following lines to line 231 in `./qmpy/__init__.py` (after `proj.allocations.add(alloc)`)

```
import django
try:
     django.setup()
except: pass
```

Does this fix your issue (if you haven't resolved it already)?
