### ISSUE TITLE
IncompletePhaseError Not Defined

### ISSUE THREAD

**Issue by jeffwdoak** [wolverton-research-group/qmpy#16]
The `IncompletePhaseError` error, which is used once, on line 351 of analysis/thermodynamics/phase.py is not defined in qmpy (at least in my older version of qmpy, in which the line is 307). I discovered this while trying to create a Phase object directly from a Calculation object and from a FormationEnergy object.

**Comment by hegdevinayi** [comment]
I think it was a typo and should have been `PhaseError` instead. Fixed in 459ff10cbb8fb74fc1a141261e102a8b76db9c08
