### ISSUE TITLE
Question with Database Setup

### ISSUE THREAD

**Issue by MShreyas1** [wolverton-research-group/qmpy#17]
Upon downloading the database, and setting it up successfully in my local MySQL database, I then changed the settings to match my local database name, USER, etc. However, when running qmpy and performing the most basic of queries as done in the tutorials, I keep getting the error django.db.utils.OperationalError: (1049, "Unknown database 'qmdb_dev'"). I have changed the database name in qmpy's settings.py from qmdb_dev, and I am unsure where I am getting this change. 

Unfortunately I am not very experienced with MySQL, so any help would be greatly appreciated.

Thanks very much!

**Comment by WardLT** [comment]
Could you try reinstalling qmpy (e.g., calling `python setup.py install` one more time)? What may have happened is the "settings.py" file you edited may not be the one being read by Python when you launch qmpy. 

This may not work with qmpy not being fully installed, but this will show you where qmpy is installed on your computer: ` python -c "from qmpy import db; print db.__path__"`

If that is different from the file you edited, reinstalling qmpy should fix your problem.

**Comment by MShreyas1** [comment]
Your fix has worked, thanks very much for the quick reply!
