### ISSUE TITLE
Possible to get structures based on composition

### ISSUE THREAD

**Issue by MShreyas1** [wolverton-research-group/qmpy#18]
I have been playing around recently with the the composition class and structures, and was wondering if it would be possible to get access to a list of structures in the database given a composition? I tried structure.objects.get, but it does not like my composition name input. ( Structure matching query does not exist) for nearly all structures. Any input would be great.

Also, can one get a list of structures or entries that are returned for a given composition? i.e. is there a way to bypass the error that says there are more than one entries/ calculations returned?

Thanks

**Comment by hegdevinayi** [comment]
@MShreyas1, something along the following lines should work:
>>> c = Composition.get('Al2O3')
>>> c.entries 
# returns a list of non-duplicate entries
>>> c.entry_set.all()
# returns a list of *all* entries associated with the composition object.

In each case, entry.structure should let you access the structure object. For example, c.entries[0].structure is the structure object of the first entry in the list returned by c.entries above.
