### ISSUE TITLE
Problem importing qmpy

### ISSUE THREAD

**Issue by gmguarino** [wolverton-research-group/qmpy#22]
I have installed just installed qmpy and am trying to import it in my python shell (in an anaconda3 environment) and I get the following error:

`File "/anaconda3/envs/python2/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 17, in <module>
    raise ImproperlyConfigured("Error loading MySQLdb module: %s" % e)
django.core.exceptions.ImproperlyConfigured: Error loading MySQLdb module: dlopen(/anaconda3/envs/python2/lib/python2.7/site-packages/_mysql.so, 2): Library not loaded: libmysqlclient.18.dylib
  Referenced from: /anaconda3/envs/python2/lib/python2.7/site-packages/_mysql.so
  Reason: image not found`

I am new at mysql but I think I set up the database properly and updated the settings.py with the details of the database. What can I do to fix this?

Thank you,
Giuseppe

**Comment by hegdevinayi** [comment]
@gmguarino, the error is something to do with the MySQL-python library. Can you try doing "pip install mysqlclient" in your anaconda environment?

**Comment by gmguarino** [comment]
Thanks a lot, that seems to work!
