### ISSUE TITLE
calculation.py read_outcar_settings()

### ISSUE THREAD

**Issue by mohanliu** [wolverton-research-group/qmpy#26]
ISPIN is not in calc.input.settings
but calculation.py wont run read_outcar_settings() once self.settings exists.
Eventually, this will cause 'ISPIN' keyerror for read_magmoms()

**Comment by hegdevinayi** [comment]
I have removed this looking up of `qmpy.Calculation.settings` when parsing OUTCARs. Now all parsing is based on info present in the OUTCAR file itself.
