### ISSUE TITLE
Structure.translate only changes .coords, but not the actual .sites data

### ISSUE THREAD

**Issue by mfkoerner** [wolverton-research-group/qmpy#37]
https://github.com/wolverton-research-group/qmpy/blob/3ead44202a5eb3302da5847b8034ce71e7dca10a/qmpy/materials/structure.py#L1462

Begin with any structure from the database:
```
import qmpy
from django.db.models import F
icsd = qmpy.Structure.objects.filter(
    entry__meta_data__value='icsd', 
    label='input',
    entry__id = F('entry__duplicate_of__id')
    )
ourstructure = icsd[0]
```
Then try to translate it
`translated = ourstructure.translate([.5, .5, .5], cartesian=False, in_place=False)`

coords are translated, sites are not
```
print(translated.coords)
print(ourstructure.coords)
print(translated.sites)
print(ourstructure.sites)
```

This is a problem for me because I am trying to translate one representation of a Perovkite into another and want the Wyckoff sites to transform when I translate the structure.

**Comment by tachyontraveler** [comment]
Thanks for reporting the bug. It is fixed now.
