### ISSUE TITLE
Required Packages

### ISSUE THREAD

**Issue by huanyu-li** [wolverton-research-group/qmpy#43]
Hi, Some required packages' latest versions require python>=3.5. Such as scipy, networkx, ase, pexpect and scimitar-learn which do not have specific version number in setup.py.

**Comment by tachyontraveler** [comment]
Thanks for the suggestion. We're pulling a major update to the qmpy within a week from now and this issue will be addressed in it.

**Comment by tachyontraveler** [comment]
This issue is addressed in the current master branch. Pip build will be updated soon.
