### ISSUE TITLE
Periodicity of structures

### ISSUE THREAD

**Issue by lmj1029123** [wolverton-research-group/qmpy#91]
Hi,

I am wondering whether there is a way to know the periodicity of the structures in the database. When I use the structure_to_atoms() function to convert the structure to ASE atoms, the pbc for all structures are false. Are they all non-periodic structures? Thanks!

best,
Mingjie

**Comment by tachyontraveler** [comment]
Hi! Technically, all structures in OQMD are periodic in all three dimensions. The DFT simulation software that OQMD uses is the Vienna Ab-initio Simulation Package (VASP). You may refer to their documentation and related forums to gather more details on how non-periodic structures are represented within VASP.
