### ISSUE TITLE
Optimade info endpoints

### ISSUE THREAD

**Issue by skaromny** [wolverton-research-group/qmpy#92]
Sorry guys for bothering, I cannot find introspective Optimade endpoints at your server.
This one http://oqmd.org/optimade/info gives 404 error.
Are there any?

**Comment by skaromny** [comment]
Please see https://github.com/Materials-Consortia/OPTiMaDe/blob/develop/optimade.rst#info-endpoints

**Comment by tachyontraveler** [comment]
Hi! Our current OPTiMaDe and OQMD API endpoints are given here: http://oqmd.org/api/
But we'll update it to receive endpoint info at http://oqmd.org/optimade/info within a couple of months when we roll out an update to the website along with updates to qmpy on python (2 to 3), Django, etc. That version of qmpy and website will be fully compatible with OPTiMaDe 1.0 specification. 
Thanks for reporting and I'll keep this issue open until we do the aforementioned update.

**Comment by tachyontraveler** [comment]
OPTiMaDe upgrade is finished at `oqmd.org/optimade`. The `info` endpoint is now available at http://oqmd.org/optimade/info
